
package org.retal.table.ejb.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "statistics", targetNamespace = "http://retal.org/logiweb/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Statistics {


    /**
     * 
     * @param getLatestOrdersRequest
     * @return
     *     returns org.retal.table.ejb.ws.GetLatestOrdersResponse
     */
    @WebMethod
    @WebResult(name = "getLatestOrdersResponse", targetNamespace = "http://retal.org/logiweb/ws", partName = "getLatestOrdersResponse")
    public GetLatestOrdersResponse getLatestOrders(
        @WebParam(name = "getLatestOrdersRequest", targetNamespace = "http://retal.org/logiweb/ws", partName = "getLatestOrdersRequest")
        GetLatestOrdersRequest getLatestOrdersRequest);

}
