
package org.retal.table.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.3.2 Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "statisticsService", targetNamespace = "http://retal.org/logiweb/ws",
    wsdlLocation = "http://localhost:8080/logiweb/ws/descriptor.wsdl")
public class StatisticsService extends Service {

  private static final URL STATISTICSSERVICE_WSDL_LOCATION;
  private static final WebServiceException STATISTICSSERVICE_EXCEPTION;
  private static final QName STATISTICSSERVICE_QNAME =
      new QName("http://retal.org/logiweb/ws", "statisticsService");

  static {
    URL url = null;
    WebServiceException e = null;
    try {
      url = new URL("http://localhost:8080/logiweb/ws/descriptor.wsdl");
    } catch (MalformedURLException ex) {
      e = new WebServiceException(ex);
    }
    STATISTICSSERVICE_WSDL_LOCATION = url;
    STATISTICSSERVICE_EXCEPTION = e;
  }

  public StatisticsService() {
    super(getWsdlLocation(), STATISTICSSERVICE_QNAME);
  }

  public StatisticsService(WebServiceFeature... features) {
    super(getWsdlLocation(), STATISTICSSERVICE_QNAME, features);
  }

  public StatisticsService(URL wsdlLocation) {
    super(wsdlLocation, STATISTICSSERVICE_QNAME);
  }

  public StatisticsService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, STATISTICSSERVICE_QNAME, features);
  }

  public StatisticsService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public StatisticsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   * Returns implementation of {@link Statistics}.
   * @return returns Statistics
   */
  @WebEndpoint(name = "statisticsSoap11")
  public Statistics getStatisticsSoap11() {
    return super.getPort(new QName("http://retal.org/logiweb/ws", "statisticsSoap11"),
        Statistics.class);
  }

  /**
   * Returns implementation of {@link Statistics}.
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns Statistics
   */
  @WebEndpoint(name = "statisticsSoap11")
  public Statistics getStatisticsSoap11(WebServiceFeature... features) {
    return super.getPort(new QName("http://retal.org/logiweb/ws", "statisticsSoap11"),
        Statistics.class, features);
  }

  private static URL getWsdlLocation() {
    if (STATISTICSSERVICE_EXCEPTION != null) {
      throw STATISTICSSERVICE_EXCEPTION;
    }
    return STATISTICSSERVICE_WSDL_LOCATION;
  }

}
